- core_admin/tno/skybotoutput.py
- core_admin/tno/views.py
- dashboard/src/assets/sass/light-bootstrap-dashboard.css
- dashboard/src/routes/app.jsx
- dashboard/src/utils.js
- dashboard/src/views/FilterObject/FilterObject.jsx
- dashboard/src/views/FilterObject/Panel.jsx
- dashboard/src/views/GetPointings/Get.jsx
- dashboard/src/views/ObjectList/CustomList.jsx
- dashboard/src/views/ObjectList/ObjectList.jsx
- dashboard/src/views/SolarSystems/SolarSystems.jsx
and change querys to retrive list status.
> Fixed layouts and organize filterObject interface. 

- dashboard/package.json
- dashboard/src/views/Astrometry/PraiaHistory.jsx
- dashboard/src/views/FilterObject/FilterObjectTable.jsx
- dashboard/src/views/GetPointings/GetPointings.jsx
- dashboard/src/views/ObjectList/CustomList.jsx
- dashboard/yarn.lock
A correção foi feita com um update das dependências do react-bootstrap-table-next
O update corrigiu 2 erros:
- Show total 
- DoubleClick
> Closed #58 - error with double event Click on all datagrid

- core_admin/predict/views.py
- dashboard/src/views/Prediction/History.jsx
- dashboard/src/views/Prediction/PredictionApi.jsx
- dashboard/src/views/RefineOrbit/History.jsx
> insertion of automatic reload in tables

- core_admin/tno/skybot/plot_ccds_objects.py
Fixed function that converts coordinates. was wrong for negative values
> Fixed CCD x Asteroid plot bug on skybot interface.

- dashboard/src/views/Astrometry/AsteroidRunDetail.jsx
- dashboard/src/views/Astrometry/Log.jsx
- dashboard/src/views/Astrometry/PraiaApi.jsx
- dashboard/src/views/RefineOrbit/Log.jsx
It was inserted a dialog box  to read astrometry output files.
> Astrometry output 2

- core_admin/common/views.py
- core_admin/coreAdmin/settings.py
- core_admin/praia/pipeline/astrometry.py
- core_admin/praia/pipeline/register.py
- core_admin/tno/condor.py
- env_template
Foi criado um conjunto de configurações para o acesso a Condor API. 
Foi criado um método que permite buscar o histórico de um Job já terminado.
> Setting condor api

- dashboard/src/views/Prediction/PredictionApi.jsx
A get request was written with a patch request.
> Fixing API Request

- dashboard/.dockerignore
- frontend/.dockerignore
- frontend/Dockerfile
> Build frontend image

- frontend/src/components/AstrometryAsteroid.js
- frontend/src/components/AstrometryDetail.js
- frontend/src/components/PredictionOccultation.js
- frontend/src/components/PredictionOccultationAsteroid.js
- frontend/src/components/RefineOrbit.js
- frontend/src/components/RefineOrbitDetail.js
- frontend/src/components/utils/CustomTable.js
**Refine Orbit**
---
**Prediction Occultation**
---
**Astrometry**
> Fixing bugs and improving the appearance of pages

- frontend/src/components/RefineOrbitDetail.js
> Fixing small bugs of missing logs in case of refinement failure and implementing toggle button to see error message

- frontend/src/api/Praia.js
- frontend/src/components/AstrometryDetail.js
- frontend/src/components/PredictionOccultation.js
- frontend/src/components/PredictionOccultationDetail.js
- frontend/src/components/RefineOrbit.js
- frontend/src/components/RefineOrbitAsteroid.js
- frontend/src/components/RefineOrbitDetail.js
- frontend/src/components/utils/CustomChart.js
> Fixing bugs of API integration and associating status colors with plot colors

- frontend/src/components/AstrometryAsteroid.js
- frontend/src/components/AstrometryDetail.js
- frontend/src/components/AstrometryHistory.js
- frontend/src/components/OccultationCalendar.js
- frontend/src/components/PredictionOccultation.js
- frontend/src/components/PredictionOccultationAsteroid.js
- frontend/src/components/PredictionOccultationDetail.js
- frontend/src/components/RefineOrbit.js
- frontend/src/components/RefineOrbitAsteroid.js
- frontend/src/components/RefineOrbitDetail.js
- frontend/src/theme/MaterialTheme.js
> Establishing icon tag standard

- frontend/src/Drawer.js
- frontend/src/api/SearchSsso.js
- frontend/src/components/SearchSsso.js
- frontend/src/components/SearchSssoDetail.js
- frontend/src/components/utils/CustomList.js
Created the Search SSSo Detail screen
> Search ssso detail material

- frontend/src/components/AstrometryDetail.js
- frontend/src/components/AstrometryHistory.js
- frontend/src/components/PredictionOccultation.js
- frontend/src/components/PredictionOccultationDetail.js
- frontend/src/components/RefineOrbit.js
- frontend/src/components/RefineOrbitAsteroid.js
- frontend/src/components/RefineOrbitDetail.js
- frontend/src/components/SkyBotRun.js
Fixed bug execution time presentation on some screens
> Fixed execution time presentation

- frontend/src/components/Skybot.js
> Skybot run

- frontend/src/components/Skybot.js
- frontend/src/components/utils/CustomLog.js
Fixed a Bug on Astrometry Asteroid
> Fix bug astrometry asteroid

- core_admin/tno/skybot/server.py
> Changed the skybot limit

- frontend/src/components/FilterObjectsDetail.js
- frontend/src/components/Pointings.js
- frontend/src/components/SearchSsso.js
Rounded table columns requested
> Columns requested rounded

- frontend/src/Drawer.js
- frontend/src/components/AstrometryAsteroid.js
- frontend/src/components/AstrometryHistory.js
- frontend/src/components/Dashboard.js
- frontend/src/components/FilterObjects.js
- frontend/src/components/Pointings.js
- frontend/src/components/PointingsDetail.js
- frontend/src/components/SkybotAsteroid.js
- frontend/src/components/utils/CustomTable.js
- frontend/src/theme/MaterialTheme.js
> Fixing bugs and improving things

- frontend/src/Drawer.js
> Change submit menu

- frontend/src/Drawer.js
- frontend/src/components/Skybot.js
> Change submit sentence

- core_admin/tno/skybotoutput.py
- core_admin/tno/views.py
- frontend/src/App.js
- frontend/src/Drawer.js
- frontend/src/Login.js
- frontend/src/api/Auth.js
- frontend/src/api/Filter.js
- frontend/src/api/Occultation.js
- frontend/src/api/Orbit.js
- frontend/src/api/Pointings.js
- frontend/src/api/Praia.js
- frontend/src/api/Prediction.js
- frontend/src/api/SearchSsso.js
- frontend/src/api/Skybot.js
- frontend/src/components/AstrometryAsteroid.js
- frontend/src/components/AstrometryDetail.js
- frontend/src/components/Dashboard.js
- frontend/src/components/FilterObjects.js
- frontend/src/components/FilterObjectsDetail.js
- frontend/src/components/Occultations.js
- frontend/src/components/OccultationsDetail.js
- frontend/src/components/PredictionOccultationAsteroid.js
- frontend/src/components/RefineOrbitAsteroid.js
- frontend/src/components/utils/CustomFooter.js
- frontend/src/components/utils/CustomToolbar.js
> Authentication

- frontend/src/api/Prediction.js
- frontend/src/components/PredictionOccultationDetail.js
> Add log button prediction

- frontend/src/Drawer.js
- frontend/src/components/Skybot.js
> Fixed date bug

- frontend/src/components/AstrometryDetail.js
- frontend/src/components/AstrometryHistory.js
- frontend/src/components/FilterObjects.js
- frontend/src/components/Pointings.js
- frontend/src/components/PredictionOccultation.js
- frontend/src/components/PredictionOccultationDetail.js
- frontend/src/components/RefineOrbit.js
- frontend/src/components/RefineOrbitDetail.js
- frontend/src/components/SearchSsso.js
- frontend/src/components/Skybot.js
- frontend/src/components/SkybotDetail.js
Changed the details position on many tables
> Changes done

- frontend/src/components/AstrometryAsteroid.js
- frontend/src/components/AstrometryDetail.js
- frontend/src/components/AstrometryHistory.js
- frontend/src/components/FilterObjectsDetail.js
- frontend/src/components/Pointings.js
- frontend/src/components/PointingsDetail.js
- frontend/src/components/PredictionOccultation.js
- frontend/src/components/PredictionOccultationDetail.js
- frontend/src/components/RefineOrbit.js
- frontend/src/components/RefineOrbitDetail.js
- frontend/src/components/SearchSsso.js
- frontend/src/components/Skybot.js
- frontend/src/components/SkybotAsteroid.js
- frontend/src/components/SkybotDetail.js
Changed numerical values position e formatted several columns
> Changed_numerical_values_position

- frontend/src/components/AstrometryDetail.js
- frontend/src/components/AstrometryHistory.js
- frontend/src/components/Pointings.js
- frontend/src/components/PredictionOccultation.js
- frontend/src/components/PredictionOccultationDetail.js
- frontend/src/components/RefineOrbit.js
- frontend/src/components/RefineOrbitDetail.js
- frontend/src/components/SearchSsso.js
- frontend/src/components/Skybot.js
- frontend/src/components/SkybotAsteroid.js
- frontend/src/components/SkybotDetail.js
Abbreviated columns on many tables
> Abbreviate columns title

- frontend/src/components/FilterObjects.js
Filter objects save button color changed from secondary to primary
> Save button color changed

- frontend/src/api/Praia.js
- frontend/src/components/AstrometryDetail.js
Fixed the astrometry detail pagination
> Astrometry Detail Pagination Fix

- core_admin/orbit/views.py
- frontend/src/Drawer.js
- frontend/src/api/Input.js
- frontend/src/components/JohnstonArchives.js
- frontend/src/components/JohnstonArchivesDetail.js
- frontend/src/components/ObservFiles.js
- frontend/src/components/OrbitalParameterFiles.js
- frontend/src/components/PointingsDetail.js
Created the Johnston main  and details screen.
Fixed some issues in other pages.
> Interface johnston

- core_admin/orbit/serializers.py
- frontend/src/Login.js
- frontend/src/api/Orbit.js
- frontend/src/components/OrbitalParameterFiles.js
> Orbital parameter details

- core_admin/praia/pipeline/astrometry.py
- core_admin/praia/pipeline/bsp_jpl.py
- core_admin/praia/pipeline/ccd_image.py
- core_admin/tno/des_ccds.py
- env_template
Foi corrigido erro que multiplicava as threads usadas para download dos CCDs, agora os downloads são enfileirados por objeto e depois em paralelo por ccd.
> Fixed multiple thread errors when downloading CCDs

- core_admin/praia/pipeline/astrometry.py
- core_admin/tno/des_ccds.py
- frontend/src/api/Filter.js
- frontend/src/components/FilterObjects/FilterObjects.js
- frontend/src/components/FilterObjects/FilterObjectsDetail.js
Os parâmetros usados no filtro não estavam sendo enviados, para a função que cria a lista. 
Isso causava um erro em que a lista era criada considerando apenas a classe do objeto.
> Fixed error when creating a list of objects 

- TODO.md
- core_admin/coreAdmin/settings.py
- core_admin/praia/pipeline/astrometry.py
- core_admin/praia/pipeline/ccd_image.py
- core_admin/praia/pipeline/register.py
- core_admin/tno/apps.py
- core_admin/tno/db.py
- core_admin/tno/skybotoutput.py
the query that returns the CCDs to be processed, was not ignoring the notes where the object was outside the CCD. now a condition has been added that checks if the CCDNUM is different from null.
> Fixed Astrometry stage CCDs without object

- core_admin/common/views.py
- core_admin/orbit/refine_orbit.py
- core_admin/praia/views.py
- core_admin/tno/jdutil.py
Foi alterada a forma como é gerado o período inicial e final utilizado no plot de astrometria. 
agora as datas são lidas do arquivo de input Astrometry.
> Changed method to retrieve period of refine orbit plots

- core_admin/praia/pipeline/astrometry.py
- core_admin/praia/pipeline/register.py
- core_admin/praia/views.py
- frontend/src/api/Praia.js
- frontend/src/components/Astrometry/AstrometryAsteroid.js
- frontend/src/components/Astrometry/AstrometryHistory.js
- frontend/src/components/helpers/CustomChart.js
- frontend/src/components/helpers/CustomDialog.js
> Small fixes before the thesis

- frontend/src/components/Occultation/OccultationDetail.js
Component was being loaded before the data, so the values were undefined.
> Fixing Aladin marking wrong position

- README.md
- Removing non-existing paths navigation
> Small changes in README.md file

- core_admin/des/dao/skybot_job_result.py
- core_admin/des/views/skybot_job_result.py
- core_admin/tno/db.py
An endpoint was created that returns every night that has already had exposures executed by skybot.
> Exposures executed by skybot

- frontend/src/pages/Skybot/Asteroid.js
- frontend/src/pages/Skybot/Detail.js
- frontend/src/pages/Skybot/index.js
> Adding explicit summary of ccd plot

- core_admin/des/dao/exposure.py
- core_admin/des/dao/skybot_job_result.py
- core_admin/des/views/exposure.py
- core_admin/des/views/skybot_job_result.py
Fixed error in returning the endpoint des/exposure/count_by_period when the period had no exposure.
> Fixed error in Skybot Calendar

- frontend/src/components/Chart/CCD.js
- frontend/src/pages/Skybot/Asteroid.js
- frontend/src/pages/Skybot/index.js
Pequenas modificações pedidas após reunião de validação e pelo Glauber
> Fixes and features asked on validation

- frontend/src/components/Chart/CalendarHeatmap.js
- frontend/src/pages/Skybot/Detail.js
- frontend/src/pages/Skybot/index.js
- frontend/src/pages/Skybot/styles.js
> Small changes after meeting

- core_admin/des/skybot/pipeline.py
- core_admin/des/views/skybot_job.py
- frontend/src/pages/Skybot/Detail.js
- frontend/src/pages/Skybot/index.js
> Fixing CCD count bug and some small changes asked in the last meeting

- core_admin/des/views/exposure.py
- frontend/src/components/Chart/CcdsDownloadedGrouped.js
- frontend/src/pages/Download/Detail.js
- frontend/src/pages/Download/index.js
- frontend/src/pages/Download/styles.js
- frontend/src/pages/Skybot/Detail.js
> Fixed and features after Download page validation

- core_admin/common/views.py
- core_admin/des/dao/skybot_job_result.py
- core_admin/des/skybot/pipeline.py
- core_admin/des/views/skybot_job.py
- core_admin/tno/db.py
3 queries were created that return the amount of asteroids, ccds and positions grouped by dynclass for a job.
> Summary ccds, asteroids and posicitions by class

- backend/Dockerfile
- backend/coreAdmin/__init__.py
- backend/coreAdmin/celery.py
- backend/coreAdmin/settings.py
- backend/requirements.txt
- backend/start.sh
- backend/start_beat.sh
- backend/start_worker.sh
- backend/tno/tasks.py
- docker-compose-development-template.yml
- local_settings_template.py
Foi configurado o serviço Celery + Rabbitmq para execução de tarefas em background. 
É necessário atualizar o arquivos locais do docker-compose.yml e local_vars.py para adicionar as modificações. 
Por favor compare os arquivos docker-compose-template e local_settings_template com seus arquivos locais e adicione as mudanças.
> Added Celery + Rabbitmq

- backend/des/views/observation.py
- frontend/src/pages/OrbitTrace/Asteroid.js
- frontend/src/pages/OrbitTrace/Detail.js
- frontend/src/pages/OrbitTrace/index.js
- frontend/src/pages/PredictOccultation/Asteroid.js
- frontend/src/pages/PredictOccultation/Detail.js
- frontend/src/pages/PredictOccultation/index.js
As alterações estão listadas na issue  #691
> Alterações no dashboard apos a reunião de validação

- frontend/src/components/PublicPortal/Header/index.js
- frontend/src/components/PublicPortal/Header/styles.js
The LIneaA logo was added to the Header and the standard color of LineA products was added to the background
> Added LIneA logo on Header

- .devcontainer/Dockerfile
- frontend/src/components/List/index.js
- frontend/src/components/PublicPortal/Header/index.js
- frontend/src/components/PublicPortal/Header/styles.js
- frontend/src/pages/Occultation/Detail.js
Implementa as tasks e correções relativas à Issue #703.
- Linhas apresentando valores ou texto 'null' são ocultados na exibição do componente.
- Arredondamentos de valores foram revistos para todos os campos.
- Foi adicionado campo 'Creation Date' para ser exibido no componente.
> Object parameters and exhibition update

- frontend/src/components/PublicPortal/Header/index.js
- frontend/src/components/PublicPortal/Header/styles.js
> remove sign in in public page

- frontend/src/components/PublicPortal/Banner/index.js
> alignment adjustment in the paragraph and slight invisibility in the white border.

- frontend/src/components/PublicPortal/Footer/FooterSupporters.js
- frontend/src/components/PublicPortal/Footer/styles.js
- frontend/src/pages/PublicPortal/Home/index.js
- frontend/src/pages/PublicPortal/Home/styles.js
- frontend/src/routes/index.js
a new file was created, where it calls the `Supporters` and `Footer components`, now making `Supporters` on all pages, next to the footer.
> 728 footer changes

- frontend/src/components/LandingPage/Header/index.js
- frontend/src/components/PredictionEventsFilter/index.js
- frontend/src/components/Toolbar/index.js
- frontend/src/contexts/AuthContext.js
- frontend/src/pages/PredictOccultation/Detail.js
- frontend/src/pages/PredictOccultation/index.js
- frontend/src/routes/index.js
- frontend/src/services/api/Auth.js
As rotas foram separadas entre publico e dashboard.
Todas as todas do dashboard estão como privadas, necessitam de autenticação para acessar. 
Após Login ou Logout é redirecionado para /dashboard.
Foi corrigido bug de perda de sessão após refresh da página. 
Foi corrigido erro ao submeter um novo job de predição, a tela ficava em branco após clicar em submeter.
Foi alterado o intervalo de atualização das barras de progresso para a tela de predição.
> Area privada do dashboard agora está protegida por autenticação.

- frontend/src/pages/PredictOccultation/Detail.js
- pipelines/src/asteroid.py
Adicionei uma checagem na quantidade de eventos,
> Fixed #779 - Error when registering objects with 0 events

- backend/tno/asteroid_table_build.py
Módulo Python automatizado para construção de uma tabela de dados de asteroides por meio do download, processamento e cruzamento de informações dos bancos de dados mpcorb_extended do Minor Planet Center e ssoBFT do IMCCE. Inclui funcionalidades como download automatizado, processamento de dados, cruzamento, classificação de classes dinâmicas, registro de eventos e salvamento de dados. Importe a função asteroid_table_build ou execute-a como programa principal para facilitar o manuseio dos dados. Certifique-se de ter instalados os pacotes Python necessários (requests, pandas, numpy). Observação: URLs e etapas de processamento podem exigir atualizações.
> Construção e atualização da tabela completa de asteroides do MPC

- predict_occultation/src/predict_occultation/pipeline/occ_path_coeff.py
Refactored code to accurately integrate post-occultation scientific prediction data—apparent magnitude, drop magnitude, and apparent diameter—into each occultation prediction entry. This update ensures data is correctly ingested to the tno_occultation table.
> Fixes the error caused during occultation results ingestion in database.

- frontend/src/pages/PredictionEvents/Detail.js
correction of card layout, now the cards have the same size as the largest
> correction of card layout

- frontend/src/App.js
- frontend/src/components/AsteroidSelect/AsteroidNameSelect.js
- frontend/src/components/AsteroidSelect/AsteroidSelect.js
- frontend/src/components/AsteroidSelect/BaseDynclassSelect.js
- frontend/src/components/AsteroidSelect/DynclassSelect.js
- frontend/src/components/AsteroidSelect/FilterTypeSelect.js
- frontend/src/components/GeoFilter/index.js
- frontend/src/components/MaginitudeSelect/index.js
- frontend/src/components/PredictionEventsFilter/index.js
- frontend/src/components/SolarTimeFilter/index.js
- frontend/src/pages/PublicPortal/Home/index.js
The Prediction Filter component had its entire layout red……esigned to be compatible with all screen sizes.
> Closed #863  Prediction Filter layout

- backend/tno/views/occultation.py
- frontend/src/pages/PredictionEvents/Detail.js
Allows filtering local solar time over midnight.
> Local solar time filtering.

- frontend/src/pages/PublicPortal/Header/index.js
Ao atingir a largura 600px os links do menu entrara em um icone (hamburguer)
> menu hamburguer no header em telas menores que L 600px

- frontend/src/pages/PredictionEvents/Detail.js
Modifica alguns textos na pagina de detalhes das predições
> Modifica alguns textos na pagina de detalhes das predições

- frontend/user_docs/docs/user-guide/api.md
- frontend/user_docs/mkdocs.yml
1. Documentação API atualizada e adaptada para o ingles.
2. Nome do site de documentação modificado de 'Solar System' para 'LIneA Occultation Prediction Database'
> Documentação API atualizada

- frontend/src/components/GeoFilter/index.js
- frontend/src/components/MaginitudeSelect/index.js
- frontend/src/pages/PredictionEvents/Detail.js
- frontend/src/pages/PublicPortal/AboutUs/index.js
- frontend/user_docs/docs/index.md
- frontend/user_docs/docs/release-notes.md
- frontend/user_docs/docs/user-guide/api.md
- frontend/user_docs/mkdocs.yml
Add Readthedocs default theme to the documentation
Changes 'About' section text
Updates Documentation text
Adds minor text exhibition fixes in the landing page and detail page
> 925 text fixes in the frontend and documentation

- frontend/src/components/PredictionEventsFilter/index.js
foi adicionado um botão 'help' no filtro que leva até (docs/user-guide/filter-events/)
> Closes #937 - adicao do botao help no filtro

- frontend/src/components/UniqueAsteroids/index.js
foi adicionado um botão de informação que leva para a página /docs/release-notes/
> Closes #935 -  adicao do botao de informacao

- frontend/src/components/AsteroidSelect/FilterTypeSelect.js
- frontend/src/contexts/PredictionContext.js
label de tipo de filtro padrão ao abrir o solar system, agora com a opção "Empty" para voltar ao padrão que inicia.
> Closes #936 - label de tipo de filtro padrao ao abrir o solar system

- backend/tno/asteroid_table/asteroid_dynamical_classification.py
- backend/tno/asteroid_table/asteroid_table_build.py
- backend/tno/management/commands/update_asteroid_table.py
Adiciona classe para calcular tanto skybot como astorb
Corrige problema de download do arquivo do imcce
> 952 fix tno table update

- frontend/src/components/GeoFilter/index.js
- frontend/src/components/PredictionEventsFilter/index.js
- frontend/src/components/SolarTimeFilter/index.js
- frontend/src/contexts/PredictionContext.js
- frontend/src/services/api/Occultation.js
adicionado um switch para habilitar e desabilitar os filtros de show events
> added a switch to enable and disable the show events filter

- frontend/public/index.html
> Implement google analytics

- backend/tno/views/geo_location.py
- backend/tno/views/occultation.py
Added treatment to remove pagination parameters before creating the hash that identifies queries by position.
> Fixed 951 - API 'radius' parameter bug

- backend/tno/views/occultation.py
- compose/local/docker-compose-template.yml
- frontend/src/components/MaginitudeDropSelect/index.js
- frontend/src/components/PredictionEventsFilter/index.js
- frontend/src/contexts/PredictionContext.js
- frontend/src/services/api/Occultation.js
Added Magnitude drop filter. 
Closed #976
> 968 magnitude drop filter

- backend/common/views.py
- backend/coreAdmin/urls.py
- frontend/src/components/AlertEnvironment/index.js
- frontend/src/pages/PredictionEvents/Detail.js
- frontend/src/pages/PublicPortal/Banner/index.js
- frontend/src/pages/PublicPortal/Home/index.js
- frontend/src/services/api/Auth.js
Criação de um endipoint para a pagina de desenvolvimento
> 1008 criar alertabanner destacando ser pgina dev no ambiente dev

- backend/tno/tasks.py
- frontend/src/pages/PredictionEvents/Detail.js
Corrige espaços e unidades de medida na página de detalhes
Corrige tempo da rodada do celery em tasks demoradas
> 1010 otimizacao da pagina de detalhes

- backend/tno/tasks.py
Fixies time limits in backend tasks.py celery function decorator
> Celery tasks time limits bug fix

- backend/common/views.py
- backend/tno/migrations/0008_merge_20240830_1446.py
- backend/tno/occviz.py
- backend/tno/tasks.py
- backend/tno/views/geo_location.py
- backend/tno/views/occultation.py
- predict_occultation/src/predict_occultation/pipeline/occ_path_coeff.py
- predict_occultation/src/predict_occultation/pipeline/occviz.py
Major upgrade in the occviz module. Compatibility is maintained.
Inclusion of the get_occultaiton_paths endpoint to get the object shaddow paths (main, diameter and uncertainty)
> Occviz Upgrade and  Get Occultation Paths endpoint

- backend/coreAdmin/celery.py
> fix(Autobot): autobot has been temporarily disabled

- frontend/src/contexts/AuthContext.js
- frontend/src/pages/PublicPortal/Banner/index.js
- frontend/src/pages/PublicPortal/Header/index.js
> fix(Auth): hided login button when subscription is disabled

- backend/tno/models/occultation.py
- backend/tno/prediction_map.py
- backend/tno/views/occultation.py
- frontend/src/routes/dashboard.js
now the id hash is used as identifier
the maps directory is now subdivided by dates.
garbage collector removes directories one day after the event.
Closed #1071
> feat(Predict-maps): the map identifier has been changed. 

- frontend/src/pages/PredictionEvents/Detail.js
- predict_occultation/src/predict_occultation/pipeline/occ_path_coeff.py
- predict_occultation/src/predict_occultation/pipeline/run.py
Fix error in path coeff with empty occultation csv files
Fix negative uncertainties in closest approach
Fix style in detail page for large numbers
> Major update uncertainty fixes

- backend/tno/occviz.py
- predict_occultation/src/predict_occultation/pipeline/occviz.py
casos extremos em que o caminho passava mais de uma vez pela mesma longitude por ser muito curvado foram tratados. isso introduzia falsa detecção da sombra para algumas localidades no centro da curva
> Fix cases where curved paths generated false positive locations

- backend/tno/asteroid_mpc_orbits/functions.py
- backend/tno/management/commands/predict_job_for_updated_asteroids.py
- backend/tno/management/commands/prediction_job_by_class.py
- backend/tno/predict_job.py
- Submit predictions by class and subclass via command line in chunks. 
- Fixes time range issues for automatic updates.
> Submit predictions by class and subclass via command line

- backend/newsletter/templates/base.tpl
- backend/newsletter/templates/header.html
- frontend/src/pages/PublicPortal/Login/index.js
Fixes the linea logo in the subscription email and provides more comprehensive login page.
> Subscription fixes 04

- backend/coreAdmin/celery.py
- backend/tno/tasks.py
Implements pre-caching functions, and a celery cronjob.
> Cache update automation

- .pre-commit-config.yaml
- backend/coreAdmin/celery.py
- backend/newsletter/templates/results.html
- frontend/src/components/ClosestApproachUncertaintyField/index.js
- frontend/src/components/PredictionEventsFilter/index.js
- frontend/src/pages/PublicPortal/Newsletter/EventFilterForm.js
This pull request includes several updates: a bug fix in the `ClosestApproachUncertaintyField `component to address an introduced issue, a refactor of the `results.html` template for enhanced readability in newsletter emails, comments on ESLint hooks in the `.pre-commit-config.yaml` for better configuration management, and a fix for a caching-related bug in the Celery task within `coreAdmin`. These changes collectively aim to improve clarity, functionality, and maintainability across the project.
> Multiple Fixes and Refactors for Improved Clarity and Functionality

- frontend/src/pages/PublicPortal/Login/index.js
- frontend/src/services/api/Auth.js
Updates to  ../../services/api/Auth.js and ../../pages/PublicPortal/Login/index.js were done to ensure proper redirection.
SITE_URL was fixed in production (had an extra slash at the end)
> Redirection to subcription settings on login

- frontend/src/components/Subscription/index.js
- frontend/src/pages/PredictionEvents/Detail.js
Correção no campo de email da subscrição e correção do layout dos cards da pagina de detalhes
> 1122 responsividade input da subscrição

- frontend/src/components/OccultationMap/DayTime.js
- Adds the new view for maps
- Adds the ability to download sora maps
- Adds the ability to download KMZ files
> Dynamic maps

- frontend/src/pages/AsteroidJob/AsteroidJobDetail.js
Correção da página de detalhes do asteroid job
> 1137 correcao asteroidjobs

- backend/common/views.py
- backend/coreAdmin/celery.py
- backend/coreAdmin/settings.py
- backend/tno/management/commands/create_thumbnail_maps.py
- backend/tno/models/occultation.py
- backend/tno/prediction_map.py
- backend/tno/tasks.py
- backend/tno/views/occultation.py
- frontend/src/components/OccultationMap/OccultationMapDownload.js
- frontend/src/components/PredictionEventsDataGrid/CardEvent.js
- frontend/src/pages/PredictionEvents/partials/OccultationMap/index.js
- Implements thumbnail generation for grid listed prediction
- Refactors SORA maps creation now as download only and stores them in tmp/maps
- Optimizes Download KMZ and Download Map buttons for mobile screens
- Old create_occ_maps in manage.py is works now as create_thumbnails_maps
> Thumbnails for dynamic maps

- backend/tno/tasks.py
fix: Deal with duplicated Provisional Designation in asteroid cache
> Deal with duplicated Provisional Designation in asteroid cache

- frontend/src/components/NewRelease/index.js
- frontend/src/pages/PublicPortal/Banner/index.js
Adds a new release minor banner
> 1157 faixa new release

- backend/tno/management/commands/create_thumbnail_maps.py
- backend/tno/prediction_map.py
- backend/tno/views/occultation.py
Comenta count no queryset list, usado apenas em info logging
Adiciona parametro de magnitude para limitar geração de map thumbnails
> Fix lazy load on landing page
